### ISSUE TITLE
Lexers to do

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_lexers#1]
For donate of course
https://packagecontrol.io/packages/Singularity%20Definition%20File%20Syntax

**Comment by Alexey-T** [comment]
https://packagecontrol.io/packages/Galen%20v2%2B

**Comment by Alexey-T** [comment]
Просьба сдирать списки keyword прямо из Суб лексеров, не искать их самому

**Comment by OlehL** [comment]
Ok
