### ISSUE TITLE
ballerina - 'continue'

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_lexers#10]
слово не подсвеч. проверить надо кейворды из Суб лексера

**Comment by Alexey-T** [comment]
слово `in` еще.

**Comment by Alexey-T** [comment]
слово `is`.

**Comment by Alexey-T** [comment]
слово `record`

**Comment by Alexey-T** [comment]
@OlehL ?

**Comment by OlehL** [comment]
Искал здесь: 
https://github.com/nipunsampath/ballerina-syntax-for-sublime-text-3/blob/master/ballerina.sublime-syntax
Но там таких кейвордов нет.
В спецификации к Ballerina нашел is и record, слово in не нашел.
Это точно кейворд?

**Comment by Alexey-T** [comment]
Если не нашёл, то я ошибся, это не кейворд
