### ISSUE TITLE
specman- %id

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_lexers#21]
```
<'

struct nest {
    %i1 : byte;
    %i2 : byte;
};

type test_kind : [NORMAL];

struct test {
    kind   : test_kind;
    
    %i1    : byte;
    %i2    : byte;
    %l1[8] : list of byte;
    %i3    : byte;
    %s1    : string;
    %r1    : real;
};

'>
```
что там значит %слово? переменные? может это посветить новым стилем?

**Comment by Alexey-T** [comment]
```
struct s {
    %f1: uint(bits: 16);
    %f2: uint(bits: 8);
    
 
};
```

**Comment by OlehL** [comment]
![image](https://user-images.githubusercontent.com/26593946/77542824-75a06700-6eaf-11ea-8d01-366ed5c5aa2f.png)
обозначение для физических полей, также нашел `!` . Какой стиль давать String2 и String3 или такое не стоит светить?

**Comment by Alexey-T** [comment]
StringN это для строк, надо выбрать из этих IdN Label

**Comment by OlehL** [comment]
Свободные только idBad и Label

**Comment by Alexey-T** [comment]
Label, еще TagId TagProp TagBound

**Comment by Alexey-T** [comment]
слова "me" и другие- зеленые. значит они IdVar. но IdVar надо на переменные. это переменные?

**Comment by OlehL** [comment]
> слова "me" и другие- зеленые. значит они IdVar. но IdVar надо на переменные. это переменные?

Да это переменные. Они как self в python.

**Comment by Alexey-T** [comment]
Self в питон не переменная а стандартное поле, переменные этотнапример в php- $name

**Comment by OlehL** [comment]
9a79ecfbe3ed833071517c94648a6f786117e347 добавил для !id и %id
