### ISSUE TITLE
bal- add functions to codetree

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_lexers#24]
01_100_continue.bal в тестах- имеет много ф-ций. вроде легко поймать в tree?

лучше если правило для tree будет ловить от и до. т е до скобки }. это сложнее но лучше. чем просто ловить слово с function без block begin/end.

пример как ловить- в Go

**Comment by Alexey-T** [comment]
еще на этом проверь- 01_advanced_type_client.bal

**Comment by Alexey-T** [comment]
01_advanced_type_client.bal - тут в tree какой-то адок

![ttt](https://user-images.githubusercontent.com/4154978/76338483-cb9ad980-6309-11ea-9761-7c5515f1c5a1.png)

**Comment by Alexey-T** [comment]
ok
остались еще баги

**Comment by OlehL** [comment]
Какие?
