### ISSUE TITLE
Specman- bad tree

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_lexers#35]
Templates_and_units.e - nested bad tree

**Comment by Alexey-T** [comment]
4 tree items are nested into each other

**Comment by OlehL** [comment]
it works different in synwrite and cudatext

**Comment by OlehL** [comment]
update in 0eee59a260df65c4de1bb5f0739c717fc3f8d27b

**Comment by Alexey-T** [comment]
click на "unit ..." в дереве- каретка ставится так

unit singleagent_port_map_u | like imc_base_port_map_u implementing advance_if {};

надо ставить на имя или на unit

**Comment by Alexey-T** [comment]
то же про "struct ..."

**Comment by OlehL** [comment]
обновил
