### ISSUE TITLE
specman- doubled tree items

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_lexers#39]
![Screenshot from 2020-03-27 17-20-04](https://user-images.githubusercontent.com/4154978/77765582-8091fd80-704f-11ea-93ef-078cd7473d08.png)

**Comment by Alexey-T** [comment]
![Screenshot from 2020-03-27 17-22-48](https://user-images.githubusercontent.com/4154978/77765834-e088a400-704f-11ea-955a-7c00d0206680.png)

**Comment by OlehL** [comment]
fix in 0dc786640f0f27920a3c23bd63c632d5c5de2d09
