### ISSUE TITLE
singul- file type

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_lexers#41]
чтоб определить ловлю имени (а не расширение) надо писать тип не как
ext

а как
/filename.ext

полное имя без пути с слешем

**Comment by OlehL** [comment]
а если нет расширения? Тогда как? Сделал так `/Singularity`, но так не сработало

**Comment by Alexey-T** [comment]
должно так работать, с / слешем. проверю

**Comment by Alexey-T** [comment]
надо в lowercase, т е `/singularity'
так сработало
