### ISSUE TITLE
singul- id w/o space

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_lexers#45]
```
%appenv foo
HELLOTHISIS=foo
export HELLOTHISIS
```
не светит слова (вар и команду)

**Comment by Alexey-T** [comment]
test 4
![Screenshot from 2020-04-08 08-59-04](https://user-images.githubusercontent.com/4154978/78749599-3bd36400-7977-11ea-9099-860126854cca.png)

**Comment by OlehL** [comment]
То есть надо светить `%appenv foo` полностью?

**Comment by Alexey-T** [comment]
HELLOTHISIS=foo
export HELLOTHISIS

Оно не светится как баш, если нет пробелов в начале

**Comment by Alexey-T** [comment]
можно не править.
