### ISSUE TITLE
specman: HIGH LOW CLEAR etc

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_lexers#6]
может это кейворды? проверь слова в Суб лексере плс.
![Screenshot from 2020-01-03 16-56-25](https://user-images.githubusercontent.com/4154978/71727047-1dc30880-2e4a-11ea-8765-8b97f84df08c.png)

**Comment by OlehL** [comment]
Таких кейвордов не нашёл ни в спецификации, ни в сублайм лексере.
