### ISSUE TITLE
specman/ballerina - keyword style

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_lexers#7]
предлагаю для "главных" слов юзать в .cuda-lexmap именно IdKeyword.
оно для того и есть.
для второстепенных уже лучше Id1,
для "типов" надо Id2,
Id3/Id4- как хочешь

**Comment by OlehL** [comment]
Хорошо, исправлю.

**Comment by Alexey-T** [comment]
жду...

**Comment by OlehL** [comment]
Это уже исправлено в процессе других изменений в 3-х лексерах. Проверь плс.
