### ISSUE TITLE
ballerina - class modifiers

### ISSUE THREAD

**Issue by Alexey-T** [OlehL/cuda_lexers#8]
модификаторы доступа класса- всякие public private abstract (надо искать их все в Суб лексере)
надо посветить своим цветом (это желтоватый в дефолт теме).

**Comment by OlehL** [comment]
![image](https://user-images.githubusercontent.com/26593946/74612386-9f76a900-510d-11ea-9ab8-b256c6e70211.png)

В сублайм модификатор доступа только один public записан вместе с другими ключевыми словами. Есть ли смысл тогда разделять?

**Comment by Alexey-T** [comment]
abstract object {
       public next() returns record {| T value; |}?;
    }

тут 
https://ballerina.io/spec/lang/2019R3/
нашел такие- public private abstract. они в разных местах, т ч стОит посветить.

**Comment by OlehL** [comment]
ok, сделаю
